runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /bootstrap
  static_dir: bootstrap
- url: /blobstore.*
  script: blobstore.app
- url: /assets
  static_dir: templates/assets
- url: /vendor
  static_dir: templates/vendor
- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js
- url: /img
  static_dir: templates/img

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: 2.7.11
